### ISSUE TITLE
TestAccuracy sscanf format issue

### ISSUE THREAD

**Issue by dsato80** [hulop/NavCogMapEditor#1]
It assumes to read 65535 for beacon major ID.

[main.cpp Line. 236](https://github.com/hulop/NavCogMapEditor/blob/master/tools/TestAccuracy/TestAccuracy/main.cpp#L236)
[main.cpp Line. 277](https://github.com/hulop/NavCogMapEditor/blob/master/tools/TestAccuracy/TestAccuracy/main.cpp#L236)

**Comment by chengxiong-ruan** [comment]
closing this since I've forgotten what's going on over the last 6 years lol
